Net/ThemeName "Dracula"
Net/IconThemeName "Dracula"
Gtk/CursorThemeName "Dracula-cursors"
Gtk/FontName "Lilex Nerd Font, 10"
Gtk/ReceiveRGBAVisuals 1
Gtk/IMStatusStyle "callback"
Gtk/ShellShowsAppMenu 0
Gcl/WindowScalingFactor 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/Antialias 1
Xft/RGBA "rgb"
